CREATE TABLE IF NOT EXISTS says (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    source VARCHAR(120) NOT NULL DEFAULT '',
    author VARCHAR(80) NOT NULL DEFAULT '',
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX says_public_idx (visible, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
