ALTER TABLE posts ADD COLUMN version BIGINT NOT NULL DEFAULT 1;
CREATE TABLE post_revisions (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 post_id BIGINT NOT NULL,
 snapshot JSON NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
 INDEX (post_id, id)
);
CREATE TABLE writing_drafts (
 user_id BIGINT NOT NULL,
 document_key VARCHAR(100) NOT NULL,
 version BIGINT NOT NULL,
 snapshot JSON NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id, document_key),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE reply_notifications (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 comment_id BIGINT NOT NULL UNIQUE,
 read_at TIMESTAMP NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(comment_id) REFERENCES comments(id) ON DELETE CASCADE,
 INDEX(user_id, id)
);
