package router

import (
	"github.com/gin-gonic/gin"
	"github.com/kakozane/kakozane-blog/api/internal/handler"
	"github.com/kakozane/kakozane-blog/api/internal/service"
)

func New(healthHandler *handler.HealthHandler, authHandler *handler.AuthHandler, contentHandler *handler.ContentHandler, userHandler *handler.UserHandler, commentHandler *handler.CommentHandler, likeHandler *handler.LikeHandler, eventHandler *handler.EventHandler, friendHandler *handler.FriendHandler, projectHandler *handler.ProjectHandler, pageHandler *handler.PageHandler, sayHandler *handler.SayHandler, mediaHandler *handler.MediaHandler, siteHandler *handler.SiteHandler, feedHandler *handler.FeedHandler) *gin.Engine {
	r := gin.Default()
	r.GET("/sitemap.xml", feedHandler.Sitemap)
	r.GET("/feed.xml", feedHandler.RSS)
	r.GET("/notes/feed.xml", feedHandler.NotesRSS)
	r.GET("/thinking/feed.xml", feedHandler.ThinkingRSS)
	r.GET("/says/feed.xml", feedHandler.SaysRSS)
	r.GET("/robots.txt", feedHandler.Robots)
	api := r.Group("/api/v1")
	api.GET("/health", healthHandler.Get)
	api.GET("/events", eventHandler.Stream)
	api.GET("/activity/comments", commentHandler.RecentPublic)
	api.GET("/activity/likes", likeHandler.RecentPublic)
	api.GET("/site/stats", contentHandler.PublicationStats)
	auth := api.Group("/auth")
	authHandler.RegisterSSO(auth, service.ScopeFront)
	auth.POST("/login", authHandler.FrontLogin)
	auth.POST("/register", userHandler.Register)
	auth.GET("/me", authHandler.FrontMe)
	auth.POST("/logout", authHandler.FrontLogout)
	frontProfile := api.Group("/auth", authHandler.RequireFront)
	frontProfile.PUT("/profile", userHandler.UpdateProfile)
	frontProfile.POST("/change-password", userHandler.ChangePassword)
	frontProfile.GET("/notifications", commentHandler.Notifications)
	frontProfile.PUT("/notifications/:id/read", commentHandler.ReadNotification)
	frontProfile.GET("/likes", likeHandler.Mine)
	api.GET("/posts", contentHandler.ListPosts)
	api.GET("/posts/:slug", contentHandler.GetPost)
	api.GET("/posts/:slug/related", contentHandler.RelatedPosts)
	api.GET("/posts/:slug/comments", commentHandler.PostList)
	api.GET("/posts/:slug/comments/:id/location", commentHandler.PostLocation)
	api.GET("/posts/:slug/likes", likeHandler.Post)
	api.GET("/notes", contentHandler.ListNotes)
	api.GET("/notes/series", contentHandler.ListNoteSeries)
	api.GET("/notes/:slug", contentHandler.GetNote)
	api.GET("/notes/:slug/related", contentHandler.RelatedNotes)
	api.GET("/notes/:slug/comments", commentHandler.NoteList)
	api.GET("/notes/:slug/comments/:id/location", commentHandler.NoteLocation)
	api.GET("/notes/:slug/likes", likeHandler.Note)
	api.GET("/thinking", contentHandler.ListThoughts)
	api.GET("/thinking/:slug", contentHandler.GetThought)
	api.GET("/thinking/:slug/related", contentHandler.RelatedThoughts)
	api.GET("/thinking/:slug/comments", commentHandler.ThoughtList)
	api.GET("/thinking/:slug/comments/:id/location", commentHandler.ThoughtLocation)
	api.GET("/thinking/:slug/likes", likeHandler.Thought)
	api.GET("/timeline", contentHandler.ListTimeline)
	api.GET("/timeline/years", contentHandler.TimelineYears)
	api.GET("/timeline/months", contentHandler.TimelineMonths)
	frontComments := api.Group("/posts", authHandler.RequireFront)
	frontComments.POST("/:slug/comments", commentHandler.PostCreate)
	frontComments.GET("/:slug/comments/mine", commentHandler.PostMine)
	frontComments.PUT("/:slug/comments/:id", commentHandler.PostEdit)
	frontComments.PUT("/:slug/likes", likeHandler.Post)
	frontComments.DELETE("/:slug/likes", likeHandler.Post)
	frontNotes := api.Group("/notes", authHandler.RequireFront)
	frontNotes.POST("/:slug/comments", commentHandler.NoteCreate)
	frontNotes.GET("/:slug/comments/mine", commentHandler.NoteMine)
	frontNotes.PUT("/:slug/comments/:id", commentHandler.NoteEdit)
	frontNotes.PUT("/:slug/likes", likeHandler.Note)
	frontNotes.DELETE("/:slug/likes", likeHandler.Note)
	frontThinking := api.Group("/thinking", authHandler.RequireFront)
	frontThinking.POST("/:slug/comments", commentHandler.ThoughtCreate)
	frontThinking.GET("/:slug/comments/mine", commentHandler.ThoughtMine)
	frontThinking.PUT("/:slug/comments/:id", commentHandler.ThoughtEdit)
	frontThinking.PUT("/:slug/likes", likeHandler.Thought)
	frontThinking.DELETE("/:slug/likes", likeHandler.Thought)
	api.GET("/categories", contentHandler.ListCategories)
	api.GET("/tags", contentHandler.ListTags)
	api.GET("/site", siteHandler.Get)
	api.GET("/friends", friendHandler.PublicList)
	api.GET("/projects", projectHandler.PublicList)
	api.GET("/pages", pageHandler.PublicList)
	api.GET("/pages/:slug", pageHandler.PublicGet)
	api.GET("/says", sayHandler.PublicList)
	adminAuth := api.Group("/admin/auth")
	authHandler.RegisterSSO(adminAuth, service.ScopeAdmin)
	adminAuth.POST("/login", authHandler.AdminLogin)
	adminAuth.GET("/me", authHandler.AdminMe)
	adminAuth.POST("/logout", authHandler.AdminLogout)
	admin := api.Group("/admin", authHandler.RequireAdmin)
	admin.GET("/drafts/:key", contentHandler.Draft)
	admin.PUT("/drafts/:key", contentHandler.SaveDraft)
	admin.DELETE("/drafts/:key", contentHandler.DeleteDraft)
	admin.GET("/posts/:id/revisions", contentHandler.Revisions)
	admin.POST("/posts/:id/restore", contentHandler.RestorePost)
	admin.DELETE("/posts/:id/purge", contentHandler.PurgePost)
	admin.GET("/posts", contentHandler.ListAdminPosts)
	admin.GET("/posts/:id", contentHandler.GetAdminPost)
	admin.POST("/posts", contentHandler.CreatePost)
	admin.PUT("/posts/:id", contentHandler.UpdatePost)
	admin.DELETE("/posts/:id", contentHandler.DeletePost)
	admin.GET("/categories", contentHandler.ListAdminCategories)
	admin.POST("/categories", contentHandler.CreateCategory)
	admin.PUT("/categories/:id", contentHandler.UpdateCategory)
	admin.DELETE("/categories/:id", contentHandler.DeleteCategory)
	admin.GET("/tags", contentHandler.ListAdminTags)
	admin.POST("/tags", contentHandler.CreateTag)
	admin.PUT("/tags/:id", contentHandler.UpdateTag)
	admin.DELETE("/tags/:id", contentHandler.DeleteTag)
	admin.GET("/users", userHandler.List)
	admin.POST("/users", userHandler.Create)
	admin.PUT("/users/:id", userHandler.Update)
	admin.POST("/users/:id/reset-password", userHandler.ResetPassword)
	admin.DELETE("/users/:id", userHandler.Delete)
	admin.PUT("/auth/profile", userHandler.UpdateProfile)
	admin.POST("/auth/change-password", userHandler.ChangePassword)
	admin.GET("/comments", commentHandler.AdminList)
	admin.PUT("/comments/:id/status", commentHandler.SetStatus)
	admin.PUT("/comments/:id/pin", commentHandler.SetPinned)
	admin.DELETE("/comments/:id", commentHandler.Delete)
	admin.GET("/media", mediaHandler.List)
	admin.POST("/media", mediaHandler.Upload)
	admin.DELETE("/media/:id", mediaHandler.Delete)
	admin.PUT("/site", siteHandler.Update)
	admin.GET("/friends", friendHandler.AdminList)
	admin.POST("/friends", friendHandler.Create)
	admin.PUT("/friends/:id", friendHandler.Update)
	admin.DELETE("/friends/:id", friendHandler.Delete)
	admin.GET("/projects", projectHandler.AdminList)
	admin.POST("/projects", projectHandler.Create)
	admin.PUT("/projects/:id", projectHandler.Update)
	admin.DELETE("/projects/:id", projectHandler.Delete)
	admin.GET("/pages", pageHandler.AdminList)
	admin.GET("/pages/:id", pageHandler.AdminGet)
	admin.POST("/pages", pageHandler.Create)
	admin.PUT("/pages/:id", pageHandler.Update)
	admin.DELETE("/pages/:id", pageHandler.Delete)
	admin.GET("/says", sayHandler.AdminList)
	admin.POST("/says", sayHandler.Create)
	admin.PUT("/says/:id", sayHandler.Update)
	admin.DELETE("/says/:id", sayHandler.Delete)
	return r
}
