package router

import (
	"github.com/gin-gonic/gin"
	"github.com/kakozane/kakozane-blog/api/internal/handler"
)

func New(healthHandler *handler.HealthHandler, authHandler *handler.AuthHandler, contentHandler *handler.ContentHandler, userHandler *handler.UserHandler, commentHandler *handler.CommentHandler, mediaHandler *handler.MediaHandler, siteHandler *handler.SiteHandler, feedHandler *handler.FeedHandler) *gin.Engine {
	r := gin.Default()
	r.GET("/sitemap.xml", feedHandler.Sitemap)
	r.GET("/feed.xml", feedHandler.RSS)
	r.GET("/robots.txt", feedHandler.Robots)
	api := r.Group("/api/v1")
	api.GET("/health", healthHandler.Get)
	auth := api.Group("/auth")
	auth.POST("/login", authHandler.FrontLogin)
	auth.POST("/register", userHandler.Register)
	auth.GET("/me", authHandler.FrontMe)
	auth.POST("/logout", authHandler.FrontLogout)
	frontProfile := api.Group("/auth", authHandler.RequireFront)
	frontProfile.PUT("/profile", userHandler.UpdateProfile)
	frontProfile.POST("/change-password", userHandler.ChangePassword)
	api.GET("/posts", contentHandler.ListPosts)
	api.GET("/posts/:slug", contentHandler.GetPost)
	api.GET("/posts/:slug/comments", commentHandler.PublicList)
	frontComments := api.Group("/posts", authHandler.RequireFront)
	frontComments.POST("/:slug/comments", commentHandler.Create)
	api.GET("/categories", contentHandler.ListCategories)
	api.GET("/tags", contentHandler.ListTags)
	api.GET("/site", siteHandler.Get)
	adminAuth := api.Group("/admin/auth")
	adminAuth.POST("/login", authHandler.AdminLogin)
	adminAuth.GET("/me", authHandler.AdminMe)
	adminAuth.POST("/logout", authHandler.AdminLogout)
	admin := api.Group("/admin", authHandler.RequireAdmin)
	admin.GET("/posts", contentHandler.ListAdminPosts)
	admin.GET("/posts/:id", contentHandler.GetAdminPost)
	admin.POST("/posts", contentHandler.CreatePost)
	admin.PUT("/posts/:id", contentHandler.UpdatePost)
	admin.DELETE("/posts/:id", contentHandler.DeletePost)
	admin.POST("/categories", contentHandler.CreateCategory)
	admin.PUT("/categories/:id", contentHandler.UpdateCategory)
	admin.DELETE("/categories/:id", contentHandler.DeleteCategory)
	admin.POST("/tags", contentHandler.CreateTag)
	admin.PUT("/tags/:id", contentHandler.UpdateTag)
	admin.DELETE("/tags/:id", contentHandler.DeleteTag)
	admin.GET("/users", userHandler.List)
	admin.POST("/users", userHandler.Create)
	admin.PUT("/users/:id", userHandler.Update)
	admin.POST("/users/:id/reset-password", userHandler.ResetPassword)
	admin.DELETE("/users/:id", userHandler.Delete)
	admin.PUT("/auth/profile", userHandler.UpdateProfile)
	admin.POST("/auth/change-password", userHandler.ChangePassword)
	admin.GET("/comments", commentHandler.AdminList)
	admin.PUT("/comments/:id/status", commentHandler.SetStatus)
	admin.DELETE("/comments/:id", commentHandler.Delete)
	admin.GET("/media", mediaHandler.List)
	admin.POST("/media", mediaHandler.Upload)
	admin.DELETE("/media/:id", mediaHandler.Delete)
	admin.PUT("/site", siteHandler.Update)
	return r
}
